
# If you change the .c file name, change this to match
NAME := trojansmegaquickpicks

# Add compile flags here
CFLAGS := -Wall

# Compiler to use
CC := gcc

all: $(NAME).c
	$(CC) $(CFLAGS) -o $(NAME).bin $(NAME).c

clean:
	rm -rf $(NAME).bin
